// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbCuOe07CrVyOR3H3pX2e5GQMR12QiCnk',
    appId: '1:874801429318:web:8fe6c260bc5cfc00610347',
    messagingSenderId: '874801429318',
    projectId: 'bety-dsi',
    authDomain: 'bety-dsi.firebaseapp.com',
    storageBucket: 'bety-dsi.appspot.com',
    measurementId: 'G-1Q81XWL939',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaJqyOSlQp-YstbWtysLz6XOhGyCXSYo4',
    appId: '1:874801429318:android:f69da8a71074a6a9610347',
    messagingSenderId: '874801429318',
    projectId: 'bety-dsi',
    storageBucket: 'bety-dsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUnHPOJKRT_KTPgu_ns8J6Mj-GJlXhS4M',
    appId: '1:874801429318:ios:d17f58ec068828d8610347',
    messagingSenderId: '874801429318',
    projectId: 'bety-dsi',
    storageBucket: 'bety-dsi.appspot.com',
    iosBundleId: 'com.example.betySprint1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUnHPOJKRT_KTPgu_ns8J6Mj-GJlXhS4M',
    appId: '1:874801429318:ios:d17f58ec068828d8610347',
    messagingSenderId: '874801429318',
    projectId: 'bety-dsi',
    storageBucket: 'bety-dsi.appspot.com',
    iosBundleId: 'com.example.betySprint1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbCuOe07CrVyOR3H3pX2e5GQMR12QiCnk',
    appId: '1:874801429318:web:3bf85ddb5af78a6c610347',
    messagingSenderId: '874801429318',
    projectId: 'bety-dsi',
    authDomain: 'bety-dsi.firebaseapp.com',
    storageBucket: 'bety-dsi.appspot.com',
    measurementId: 'G-R5FYZL53KT',
  );

}